version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Add assignees
    assignees:
      - "sampetherbridge"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":arrow_up:"
